c_compiler_version:    # [linux]
- '11'                 # [linux]
cxx_compiler_version:  # [linux]
- '11'                 # [linux]

abseil_cpp:
 # The future version we want to migrate to
 - '20220623.0'

# As of 2022/07/26 grpc and abseil_cpp are zipped together
grpc_cpp:
 - '1.46'

# new abseil builds are not zipped in the pinning, but should
# move in lockstep with abseil-cpp until that is removed;
# we only have these for v>=20220623.0 so far
libabseil:
 - '20220623.0'

libabseil_static:
 - '20220623.0'
